"use client";
import { useEffect, useState } from "react";
const store = "https://apps.odoo.com/apps/modules/browse?author=Modulink%20Solutions";
const whatsapp = "https://wa.me/201099023501";
const copy = {
 ar: {
 nav:["من نحن","خبراتنا","تطبيقات Odoo","كيف نعمل"], talk:"لنتحدث عن أعمالك", menu:"القائمة", close:"إغلاق القائمة", contact:"تواصل معنا",
 eyebrow:"استشارات مالية · حلول Odoo وERP", title:"رؤية مالية أوضح.", accent:"أعمال أكثر ترابطًا.", intro:"نحوّل احتياجاتك المالية والتشغيلية إلى أنظمة عملية. من الاستشارة إلى تنفيذ Odoo وتدريب فريقك، نربط التفاصيل لتعمل أعمالك بكفاءة.", explore:"اكتشف خبراتنا", note:"نفهم أعمالك أولًا، ثم نبني الحل المناسب لها.",
 panelTitle:"كل أجزاء أعمالك، في رؤية واحدة", panelSub:"من البيانات إلى القرار", demo:"تصور توضيحي لتكامل الأعمال", parts:["المالية","المبيعات","المخزون","العمليات"], panelFoot:"أنظمة مترابطة. قرارات مدروسة.",
 platforms:"خبرة مالية، مدعومة بالتكنولوجيا", platformsSub:"نربط المعرفة المحاسبية بالتطبيق العملي", partners:"منصات وشركاء",
 aboutLabel:"01 / من نحن", aboutTitle:"نفهم لغة الأرقام.", aboutAccent:"ونحوّلها إلى حلول.", about:"Modulink Solutions تجمع بين الاستشارات المالية والخبرة التقنية لتساعدك على تنظيم أعمالك وتطوير إجراءاتها. ننطلق من طريقة عمل فريقك، ونصمم الحل حول احتياجاته الحقيقية.", principles:[["فهم قبل التنفيذ","نراجع الإجراءات والتحديات قبل اقتراح أي نظام."],["حل يناسب أعمالك","نربط التحليل المحاسبي بالتنفيذ والتدريب والدعم."]],
 servicesLabel:"02 / خبراتنا", servicesTitle:"من الصورة المالية إلى التفاصيل التشغيلية.", servicesIntro:"خدمات مترابطة، تختار منها ما تحتاجه أعمالك في مرحلتها الحالية.", services:[["الاستشارات المالية","رؤية تساعدك على اتخاذ القرار","تحليل الإجراءات والبيانات المالية، وتحسين التقارير لدعم إدارة الأداء والربحية.","التحليل المالي / التقارير / تحسين الأداء"],["المراجعة والرقابة","ثقة أكبر في إجراءاتك","مراجعة العمليات وتطوير أنظمة الرقابة الداخلية للحد من الأخطاء والمخاطر التشغيلية.","مراجعة الإجراءات / الرقابة الداخلية"],["تنفيذ أنظمة Odoo وERP","نظام يعمل بطريقتك","تحليل احتياجاتك وتهيئة النظام وتخصيصه، لربط الإدارات والبيانات داخل بيئة عمل متكاملة.","تحليل العمليات / التهيئة / التخصيص"],["التدريب والدعم","فريق مستعد للعمل بكفاءة","تدريب عملي للمستخدمين ومساندة مستمرة تساعد فريقك على الاستفادة من النظام وتطوير استخدامه.","تدريب المستخدمين / الدعم / التحسين"]],
 appsLabel:"03 / تطبيقاتنا", appsTitle:"حلول عملية. متاحة على Odoo.", appsIntro:"تطبيقات Modulink Solutions لمعالجة احتياجات محددة في الإدارة المالية ونقاط البيع.", store:"جميع تطبيقاتنا على Odoo", appLink:"عرض التطبيق", appVersion:"متاح لـ Odoo 19", app1:"إقفال نقاط البيع", app1desc:"إقفال أعمى لنقاط البيع مع إيصال باللغة الإنجليزية يوضح العجز أو الزيادة، بعرض 80 مم.", app2:"الموافقات المالية", app2desc:"موافقات متعددة المستويات على الطلبات والمدفوعات والمقبوضات لتنظيم دورة الاعتماد.",
 processLabel:"04 / أسلوب العمل", processTitle:"خطوات واضحة، من أول حديث إلى التشغيل.", steps:[["نستمع ونحلل","نفهم تحدياتك ونراجع طريقة عملك الحالية."],["نحدد الطريق","نتفق على نطاق العمل والأولويات وخطة التنفيذ."],["ننـفذ وندرّب","نهيّئ الحل ونساعد فريقك على استخدامه عمليًا."],["نتابع ونطوّر","نراجع النتائج وندعم احتياجاتك مع تطور أعمالك."]],
 ctaLabel:"لنبدأ من احتياجاتك", ctaTitle:"ما الخطوة التالية لأعمالك؟", ctaText:"سواء كنت تطوّر نظامك المالي أو تبدأ رحلتك مع Odoo، يسعدنا أن نفهم ما تحتاجه.", email:"راسلنا بالبريد", footer:"نربط الخبرة المالية بالتكنولوجيا.", rights:"جميع الحقوق محفوظة.", back:"العودة للأعلى"
 },
 en: {
 nav:["About","Expertise","Odoo apps","Our approach"], talk:"Let’s talk business", menu:"Menu", close:"Close menu", contact:"Get in touch",
 eyebrow:"Financial consulting · Odoo & ERP solutions", title:"Financial clarity.", accent:"Connected business.", intro:"Turn financial and operational needs into practical systems. From consulting to Odoo implementation and team training, we connect the details that help your business work better.", explore:"Explore our expertise", note:"Your business comes first. The right solution follows.",
 panelTitle:"Your business. One connected view.", panelSub:"From information to insight", demo:"Illustrative business integration concept", parts:["Finance","Sales","Inventory","Operations"], panelFoot:"Connected systems. Informed decisions.", platforms:"Financial expertise, enabled by technology", platformsSub:"Connecting accounting knowledge with practical delivery", partners:"Platforms & partners",
 aboutLabel:"01 / About Modulink", aboutTitle:"We understand the numbers.", aboutAccent:"And make them work for you.", about:"Modulink Solutions brings financial consulting and technical expertise together to help you organize and improve your operations. We start with how your team works, then shape the solution around its real needs.", principles:[["Understand before implementing","We review your processes and challenges before recommending a system."],["Built around your business","Accounting insight connected with implementation, training, and support."]],
 servicesLabel:"02 / Our expertise", servicesTitle:"From financial perspective to operational detail.", servicesIntro:"Connected services for the needs and priorities of your business today.", services:[["Financial consulting","Clarity for better decisions","Financial process and data analysis, with better reporting to support performance and profitability.","Financial analysis / Reporting / Performance"],["Audit & internal controls","Confidence in your processes","Process reviews and stronger internal controls to reduce errors and operational risk.","Process reviews / Internal controls"],["Odoo & ERP implementation","A system that works your way","Needs analysis, configuration, and tailored solutions that connect departments and data in one environment.","Process analysis / Configuration / Customization"],["Training & support","A team ready to move forward","Practical user training and ongoing support to help your team use its system with confidence.","User training / Support / Improvement"]],
 appsLabel:"03 / Our applications", appsTitle:"Practical solutions. Available on Odoo.", appsIntro:"Modulink Solutions applications built for specific financial and point-of-sale workflows.", store:"All our apps on Odoo", appLink:"View application", appVersion:"Available for Odoo 19", app1:"POS Blind Closing", app1desc:"Blind point-of-sale closing with an English 80 mm receipt showing cash shortages or overages.", app2:"Financial Approvals", app2desc:"Multi-level approvals for orders, payments, and receipts to organize your approval workflow.",
 processLabel:"04 / Our approach", processTitle:"A clear path from first conversation to operation.", steps:[["Listen & assess","Understand your challenges and review how you work today."],["Define the path","Agree on scope, priorities, and a practical delivery plan."],["Implement & train","Configure your solution and help your team use it in practice."],["Support & improve","Review results and support your needs as your business evolves."]],
 ctaLabel:"Start with your business", ctaTitle:"What’s your next move?", ctaText:"Whether you are improving your financial systems or starting your Odoo journey, we would love to understand what you need.", email:"Send us an email", footer:"Connecting financial expertise with technology.", rights:"All rights reserved.", back:"Back to top"
 }
};
function Arrow(){return <span aria-hidden="true" className="arrow">↗</span>}
function Brand(){return <><span className="brand-mark"/><span dir="ltr"><b>modulink<span className="brand-dot">.</span></b><small>SOLUTIONS</small></span></>}
export default function Home(){
 const [lang,setLang]=useState<"ar"|"en">("en"); const [menu,setMenu]=useState(false); const t=copy[lang]; const rtl=lang==="ar";
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=rtl?"rtl":"ltr"},[lang,rtl]);
 const anchors=["about","services","work","process"];
 return <main id="home" dir={rtl?"rtl":"ltr"} className={rtl?"rtl":"ltr"}>
 <a className="skip" href="#about">{rtl?"انتقل إلى المحتوى":"Skip to content"}</a>
 <header className="header"><a className="brand" href="#home" aria-label="Modulink Solutions"><Brand/></a><nav className={menu?"nav open":"nav"} id="navigation" aria-label={rtl?"القائمة الرئيسية":"Main navigation"}>{t.nav.map((label,i)=><a key={label} href={`#${anchors[i]}`} onClick={()=>setMenu(false)}>{label}</a>)}</nav><div className="header-actions"><button className="language" onClick={()=>{setLang(rtl?"en":"ar");setMenu(false)}} aria-label={rtl?"Switch to English":"التبديل إلى العربية"}>{rtl?"EN":"عربي"}</button><a className="header-cta" href={whatsapp} target="_blank" rel="noopener noreferrer">{t.contact}<Arrow/></a><button className="menu-button" aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>{menu?t.close:t.menu}<span aria-hidden="true">{menu?"×":"☰"}</span></button></div></header>
 <section className="hero wrap" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span/>{t.eyebrow}</p><h1 id="hero-title">{t.title}<br/><em>{t.accent}</em></h1><p className="hero-intro">{t.intro}</p><div className="actions"><a className="button gold" href={whatsapp} target="_blank" rel="noopener noreferrer">{t.talk}<Arrow/></a><a className="text-link" href="#services">{t.explore}<span aria-hidden="true">↓</span></a></div><p className="hero-note"><span aria-hidden="true">✓</span>{t.note}</p></div><div className="business-visual"><div className="visual-top"><span className="mini-brand" dir="ltr">MODULINK <span>/</span> SOLUTIONS</span><span className="status-dot"/></div><p className="visual-kicker">{t.panelSub}</p><h2>{t.panelTitle}</h2><div className="system-map"><div className="system-center" dir="ltr"><b>M<span>.</span></b><small>CONNECTED BUSINESS</small></div><div className="system-nodes">{t.parts.map((part,i)=><div className="system-node" key={part}><span className="node-icon" aria-hidden="true">{["≋","↗","▦","◎"][i]}</span><span>{part}</span><i/></div>)}</div></div><div className="visual-bottom"><span>{t.panelFoot}</span><span className="visual-lines" aria-hidden="true"><i/><i/><i/><i/><i/></span></div><p className="demo-note">{t.demo}</p></div></section>
 <section className="platform-strip"><div className="wrap platform-inner"><div><strong>{t.platforms}</strong><span>{t.platformsSub}</span></div><div className="partner-logos" aria-label={t.partners}><img src="/partner-odoo.png" alt="Odoo"/><span className="logo-divider"/><img src="/partner-anevex.png" alt="Anevex"/></div></div></section>
 <section id="about" className="section wrap about"><div><p className="section-label">{t.aboutLabel}</p><h2>{t.aboutTitle}<br/><span className="muted-heading">{t.aboutAccent}</span></h2></div><div><p className="lead">{t.about}</p><div className="principles">{t.principles.map(([title,desc],i)=><div key={title}><span className="small-index">0{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div></div>)}</div></div></section>
 <section id="services" className="services-section"><div className="wrap section"><p className="section-label">{t.servicesLabel}</p><div className="section-heading"><h2>{t.servicesTitle}</h2><p>{t.servicesIntro}</p></div><div className="service-grid">{t.services.map(([title,sub,desc,tags],i)=><article className="service-card" key={title}><div className="card-top"><span className="service-icon" aria-hidden="true">{["↗","◎","▦","↔"][i]}</span><span className="index">0{i+1}</span></div><h3>{title}</h3><span className="service-sub">{sub}</span><p>{desc}</p><div className="service-tags">{tags}</div></article>)}</div></div></section>
 <section id="work" className="section wrap apps"><p className="section-label">{t.appsLabel}</p><div className="section-heading"><h2>{t.appsTitle}</h2><a className="text-link" href={store} target="_blank" rel="noopener noreferrer">{t.store}<Arrow/></a></div><p className="section-intro">{t.appsIntro}</p><div className="app-grid">{[{name:t.app1,desc:t.app1desc,slug:"pos_blind_closing_report_v2",category:"POINT OF SALE",icon:"▤"},{name:t.app2,desc:t.app2desc,slug:"order_finance_approval",category:"FINANCE & CONTROL",icon:"✓"}].map((app,i)=><article className={`app-card app-${i}`} key={app.slug}><div className="app-art"><span className="app-category">{app.category}</span><span className="app-symbol" aria-hidden="true">{app.icon}</span><span className="app-art-word" dir="ltr">{i===0?"Close with clarity.":"Approve with confidence."}</span><span className="app-watermark" aria-hidden="true">0{i+1}</span></div><div className="app-content"><span className="app-version">{t.appVersion}</span><h3>{app.name}</h3><p>{app.desc}</p><a className="text-link" href={`https://apps.odoo.com/apps/modules/19.0/${app.slug}`} target="_blank" rel="noopener noreferrer">{t.appLink}<Arrow/></a></div></article>)}</div></section>
 <section id="process" className="process-section"><div className="wrap section"><p className="section-label">{t.processLabel}</p><h2>{t.processTitle}</h2><div className="steps">{t.steps.map(([title,desc],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
 <section id="contact" className="wrap contact-section"><div className="contact-panel"><div><p className="section-label">{t.ctaLabel}</p><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p></div><div className="contact-actions"><a className="button gold" href={whatsapp} target="_blank" rel="noopener noreferrer">{t.talk}<Arrow/></a><a className="email-link" href="mailto:Modulink-eg@hotmail.com">{t.email}<span dir="ltr">Modulink-eg@hotmail.com</span></a></div></div></section>
 <footer className="wrap"><div className="footer-top"><div><a className="brand" href="#home"><Brand/></a><p>{t.footer}</p></div><div className="footer-socials" aria-label={rtl?"التواصل الاجتماعي":"Social media"}>{[["Facebook","https://www.facebook.com/Mrdulink"],["Instagram","https://www.instagram.com/modulink1?igsh=MThkeTltZno1NW9meg=="],["Telegram","https://t.me/Modulinkeg"],["Snapchat","https://www.snapchat.com/@modulink"],["WhatsApp",whatsapp]].map(([label,url])=><a key={label} href={url} target="_blank" rel="noopener noreferrer">{label}<Arrow/></a>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Modulink Solutions. {t.rights}</span><a href="#home">{t.back} ↑</a></div></footer>
 </main>
}
